### PR TITLE
version 4.4.4

### PR DESCRIPTION
**Pull request by deleolajide**
Fixed issue #6 and issue #7

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks @deleolajide , can you please include an additional commit that bumps the version to the next snapshot as per convention with how plugin artifacts go to archiva?

**Comment by deleolajide** [comment]
> Thanks @deleolajide , can you please include an additional commit that bumps the version to the next snapshot as per convention with how plugin artifacts go to archiva?

I have not done this task before. Do you have an example or notes to show me how? Thanks

**Comment by akrherz** [comment]
Just add another commit that bumps the plugin's pom version to `4.4.5-SNAPSHOT`

**Comment by deleolajide** [comment]
That was easy enough. Thank you @akrherz

**Comment by akrherz** [comment]
thanks, will merge once CI passes and then tag the release at that first commit.

**Pull request merged**
