### PR TITLE
Fix version 4 4 5

### PR DESCRIPTION
**Pull request by deleolajide**
Fixing issue #13

### CODE REVIEW

**Comment by deleolajide** [comment]
>Making sure that last commit on the master branch has a non snapshot …

That should have read **Making sure that last commit on the master branch has a snapshot …**

**Comment by wrooot** [comment]
Great work 😉

**Comment by wrooot** [comment]
@akrherz Still waiting for a download of 4.4.5 at http://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=fastpath

**Comment by akrherz** [comment]
> @akrherz Still waiting for a download of 4.4.5 at http://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=fastpath

Still unsure what is going on, but the website needed a reboot anyway, which seems to have fixed it.

**Pull request merged**
